server:
  port: 10085

spring:
  datasource:
    url: jdbc:mysql://8.130.131.122:4001/boot_admin?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456