server:
  port: 10085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot_admin?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456




#mybatis-plus:
#  mapper-locations: classpath:/src/main/resources/mapper/*.xml